project_name: dovectl
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: dovectl
    ldflags:
      - -s -w
      - -X github.com/lupinthe14th/dovectl/pkg/version.Version={{.Version}}
      - -X github.com/lupinthe14th/dovectl/pkg/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
